sudo: false
addons:
    apt:
        packages:
            - oracle-java9-installer

language: java

before_script:
  - test "x$RUN_CHECKSTYLE" != 'x' || ant -Djava.awt.headless=true download_jars install
  - test "x$RUN_CHECKSTYLE" != 'xtrue' || ant -Djava.awt.headless=true download_checkstyle

before_install:
    - unset _JAVA_OPTIONS
    - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.3-bin.tar.gz
    - tar -xzvf apache-ant-1.10.3-bin.tar.gz
    - export PATH="$(pwd)/apache-ant-1.10.3/bin:$PATH"
    - echo $(ant -version)

# skip default "install" command
install: true

matrix:
  include:
    - jdk: oraclejdk8
      env: RUN_CHECKSTYLE=true
      script: ant -Djava.awt.headless=true checkstyle
    - jdk: oraclejdk9
      script: 
          - ant -Ddisable-svnCheck=true -Djava.awt.headless=true -Drmi_force_localhost=true -Dskip.bug52310=true coverage-travis
#          - jdk_switcher use oraclejdk10
#          - ant -Ddisable-svnCheck=true -Djava.awt.headless=true -Drmi_force_localhost=true -Dskip.bug52310=true coverage-travis
#          - jdk_switcher use oraclejdk11
#          - ant -Ddisable-svnCheck=true -Djava.awt.headless=true -Drmi_force_localhost=true -Dskip.bug52310=true coverage-travis
      sudo: true # otherwise TEST_HTTPS.jmx -> analytics.usa.gov does not work
# No building with JDK9 nor JDK10 as it has a bug and will not compile JMeter
# see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8193802
#

after_success:
    - bash <(curl -s https://codecov.io/bash)
